modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="textrues_sodium_options"
version="${version}"
displayName="TexTrue's Sodium Options"
displayURL="https://github.com/Lonmo0208/Textrues-Sodium-Options"
logoFile= "icon.png"
credits="FlashyReese"
authors="TexTrue, TexTrueStudio"
description='''
Port of Reese's Sodium Options to work with Sodium on MinecraftForge/NeoForge.

Replaces Sodium Options Screen.
'''

[[mods]]
modId = "reeses_sodium_options"
version = "1.0.4"
displayName = "TexTrue's Rubidium Options (TexTrue's Sodium Options)"
description = '''
Stub, to allow mods detecting TexTrue's Rubidium Options to function as expected.
'''

[[dependencies.textrues_sodium_options]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.textrues_sodium_options]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.textrues_sodium_options]]
modId = "Sodium"
mandatory = true
versionRange = "[0.6.0,)"
ordering = "NONE"
side = "CLIENT"
